language: node_js
node_js:
  - 6.2.0

sudo: required
dist: trusty

env:
  - NODE_ENV=test

branches:
  only:
    - master
    - develop

before_install:
  # adding mongo via docker
  - docker run --name test-mongo -d -p 27017:27017 mongo
before_script:
  - webpack

