language: node_js
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
branches:
  only:
    - master
    - develop
env:
  - NODE_ENV=test
services:
  - mongodb
node_js:
  - 6.2.0
before_install:
  - npm install -g node-gyp
  - npm install
  - webpack