language: node_js
node_js:
  - 6.2.0

sudo: required
dist: trusty

env:
  - NODE_ENV=test

services:
  - mongodb

branches:
  only:
    - master
    - develop

before_install:
  - sudo apt-get install build-essential
before_script:
  - webpack

