web:
  build: .
  expose:
    - "80"
  volumes:
    - /app
  environment:
    VIRTUAL_HOST: boardofshame.app
  restart: always
  container_name: "boardofshame"
  links:
    - db

db:
  image: "mongo:latest"
  restart: always
  container_name: "boardofshame_db"